### ISSUE TITLE
Loading SVG assets in IE11

### ISSUE THREAD

**Issue by guigzz** [englercj/resource-loader#111]
Hi,

This loader, used via Pixi.js, dosn't seem to be able to load svg assets in IE11.

Here is a pen that demonstrates the issue : https://codepen.io/guigzz/pen/zRWjvw
(left is without the loader, using texture fromImage directly, and right is with the loader)

I know it's about IE but... if it cannot be fixed, is there any workaround that could be used if I really need this feature ? Thanks in advance.

Cheers

**Comment by englercj** [comment]
I investigated this, and it is due to a bug in `PIXI.BaseTexture.loadSource()`. Basically it doesn't support receiving a completely loaded SVG Image.

[This line](https://github.com/pixijs/pixi.js/blob/3c331cc2e0995796b0a679175ca0c0d8895d3ada/src/core/textures/BaseTexture.js#L396) needs to update the image type, just like [this line](https://github.com/pixijs/pixi.js/blob/3c331cc2e0995796b0a679175ca0c0d8895d3ada/src/core/textures/BaseTexture.js#L353) does. In fact the `onload` handler and the `complete` check block look so similar, they probably should just call the same function.

Anyway that causes the issue here. Because the imageType doesn't get updated (because the image has already loaded) the "load svg" path in pixi never happens and therefore the texture is never correct.

**Comment by guigzz** [comment]
Thanks a lot man !

**Comment by englercj** [comment]
I think if someone solved pixijs/pixi.js#4704 in the way I suggest it should fix your problem. If that doesn't fix it I'm not really sure, would need to dig for a while more but I don't really have time to :(

**Comment by guigzz** [comment]
I totally understand you have no time for this ;)

Just to be sure, when you say "the way I suggest" in your message, it's the fix involving the addition of a call to _updateImageType() ? Because this does notinh apparently when I try it, and I'm not really sure how it could fix the size issue,  but I might not fully understand how BaseTexture works after all...

Could you confirm that the fix should be with the -updateImageType() ?

And thank you very much for your time ! 👍

**Comment by englercj** [comment]
It doesn't just need to be called, it needs to be called at the spot that I mentioned. Just after that spot there is a check to see if it is SVG and if it is, to do all the work necessary to set the width/height ([see here](https://github.com/pixijs/pixi.js/blob/3c331cc2e0995796b0a679175ca0c0d8895d3ada/src/core/textures/BaseTexture.js#L399)).

This check fails because the imageType is not set.

**Comment by guigzz** [comment]
Yes of course, I tried to call `_updateImageType` at  the spot you mentionned. No success. 

Actually, if I force the image type to be svg and I remove all the check for image type on my way, I land on the `_loadSvgSourceUsingXhr()` function and this is where IE get stucks. Judging by all the comments in this function, IE breaks because of its "good old" data inlining bug ([see here](https://github.com/pixijs/pixi.js/issues/4073)).

Actually, I found a temp dirty workaround that consists of forcing `source.width` and `source.height` at the beginning of the `loadSource()` function, and then the code never goes into the complete callback, so never fails in the `loadSvgSourceUsingXhr` function... And it displays the texture as we would expect...

So, considering that the IE bug involved in the `loadSvgSourceUsingXhr` will never be fixed, the "real" problem appears to be the missing width and height on the source object that arrives in the `loadSource` function. Would you agree with that or do you see anything that I am missing ?

Cheers.

**Comment by englercj** [comment]
Honestly don't know, I'd have to debug on IE and see what in pixi is failing. Best bet to fix your issue is see why the code in `_loadSvgSourceUsingXhr()` isn't working for you, because it should just be running a regex on the loaded XML string got back from XHR.
