### ISSUE TITLE
i can't load a image from url

### ISSUE THREAD

**Issue by chrisyer** [englercj/resource-loader#115]
I try to load a image from `http://thirdwx.qlogo.cn/mmopen/XYrRG5UShDcrTQs7ZnsUks0uT8AqAPcwNPnwmnHef1c0a5O2ScvubY5iaB9nHCAswFCWJLicic6Z3FLWcXTEYvw1qYOQG2f9gQn/132`

param:
```
{
  name: 'avatar',
  url: 'http://thirdwx.qlogo.cn/mmopen/XYrRG5UShDcrTQs7ZnsUks0uT8AqAPcwNPnwmnHef1c0a5O2ScvubY5iaB9nHCAswFCWJLicic6Z3FLWcXTEYvw1qYOQG2f9gQn/132',
  options: {
    xhrType: PIXI.loaders.Resource.XHR_RESPONSE_TYPE.BLOB,
  },
}
```
but i find the resource's data is text

![default](https://user-images.githubusercontent.com/14369492/43989843-4bee54ba-9d84-11e8-9a6b-cae702cb549f.png)

example:
https://jsfiddle.net/w6puqrsx/8/

**Comment by themoonrat** [comment]
I've fixed your fiddle: https://jsfiddle.net/L6wn9b4p/

There were a number of things causing it not to work
1. You weren't adding the canvas element correct. I've fixed this with `document.body.appendChild(app.view);`
2. You correctly worked out that you needed to manually set a loadType, because your url has no extension, but you'd created a new options object when you were already within the options object
3. You needed to use the texture of `res.test` to create the Sprite

**Comment by chrisyer** [comment]
Thanks very much for you reply.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Dave Moore <notifications@github.com>
发送时间: Saturday, August 11, 2018 6:51:48 PM
收件人: englercj/resource-loader
抄送: Cheng; Author
主题: Re: [englercj/resource-loader] i can't load a image from url (#115)


I've fixed your fiddle: https://jsfiddle.net/L6wn9b4p/

There were a number of things causing it not to work

  1.  You weren't adding the canvas element correct. I've fixed this with document.body.appendChild(app.view);
  2.  You correctly worked out that you needed to manually set a loadType, because your url has no extension, but you'd created a new options object when you were already within the options object
  3.  You needed to use the texture of res.test to create the Sprite

―
