### ISSUE TITLE
how to load from atlas from different sources, image one url json other?

### ISSUE THREAD

**Issue by ddfire** [englercj/resource-loader#151]
hi
i need to be able to understand how to load an atlas, where the json is in one place and the png is in a diferent url 
Thanks

**Comment by englercj** [comment]
That's just two resources, a json file and an image file.

**Comment by ddfire** [comment]
And how i mix them to get all the sprites?
Thanks!!!

**Comment by englercj** [comment]
This library just downloads things, what you do with what is downloaded is up to you.

```js
loader.add('json', jsonUrl).add('img', imageUrl).load(() =>
{
    console.log(loader.resources.json);
    console.log(loader.resources.img);
});
```

**Comment by TheSenPie** [comment]
@englercj I understand his question, 
The same thing happened to me and I don't know how to solve it.
For a simple project where I had atlas.json and atlas.png in the same loader, I would do 
```
loader
  .add("images/atlas.json")
  .load(() => {
    let sprite = new Sprite(
      resources["images/atlas.json"].textures["frameId.png"]
    );
  });
```
However, now that I am using webpack and I inline assets with base64 into HTML, I have to import those assets at the top like this
```
import atlas_texture from 'assets/atlas.png;
import atlas_json from 'assets/atlas.json;
```
however, I cannot load them, in the same way, I did before.
I found a solution to do something like this
```
loader.add({url: atlas_texture, name: 'texture'}).load(() => {
  const  sheet = new Spritesheet(
    Loader.shared.resources['texture'].texture.baseTexture, 
    atlas_json
  );
  sheet.parse((...args) => {
    console.log(sheet.textures);
  });
  
});
```
However it is still not perfect, because this way I don't have my textures ready by the time I am in load()'s callback. Do you know a way to fix it? 
Also, as I talked about this issue, because my assets now are base64, I don't know how to load spine animations either. Can you provide an example of how I can do that?
