### ISSUE TITLE
Add real loaded percentage

### ISSUE THREAD

**Issue by Samsy** [englercj/resource-loader#44]
I forked the project and added few stuffs to handle a real percentage progression based on the total weight of files.

It doesnt handle request error at the moment, and slightly made few changes : 

the original 'progress' event become 'file' event and is fired everytime a file is loaded

'progress' event is fired everytime a new chunk of data has been loaded, you can access the progression percentage with ` progresstotal `

<img src=http://i.imgur.com/k9f8fvg.png>

I did it very fast for my own purpose.

If you guys want to give a hand : 

[(https://github.com/Samsy/resource-loader)]

**Comment by englercj** [comment]
A couple things to note:

- This only works with XHR requests, many loader requests are actually not xhr.
- You are marking an unnecessary preflight HEAD request, you can get those same headers from the GET request.
- Loader now has XHR knowledge which is a leak of responsibilities from Resource
- This doesn't take into account resources added mid-flight, i.e. by middlewares (parsing a sprite atlast for example).
- You could've used the existing resource progress event and some math instead of building this extra weight plumbing (https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L455-L466)

The reason I never fully implemented this and only got as far as resources exposes their individual progress is because it is completely unreliable. It only works with XHR, and only in modern browsers, and only if the server sends the right headers. If any one of those isn't true, which is often the case, then this falls apart :(

**Comment by Samsy** [comment]
I understand every points, and you are right !
I did this very fast, to make it work asap.

I needed that progression for a project, and I finally started to write my own loader with fetch and polyfills for my own purposes.

I can close this, it looks like you have great reason to not implement it :)

**Comment by englercj** [comment]
If this module didn't support IE9 then I would probably say we could load everything via XHR and just do parsing in JS. But IE9 (and a little in IE10) make this pretty hard sometimes :(
