### ISSUE TITLE
Allow setting default middleware

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#74]
It would be nice to have an API that registered "default middleware". That is, middleware that is automatically added to each loader that is created.

**Comment by bigtimebuddy** [comment]
👍  to this!

I'd like to toss out the following static Loader API idea:

- `Loader.pre(fn, prepend = false): Loader` 
Similar to `Loader.prototype.pre` but will add for all Loader instances.
- `Loader.use(fn, prepend = false): Loader` 
Similar to `Loader.prototype.use` but will add for all Loader instance.

The optional `prepend` flag can be enabled to unshift the middleware, otherwise it is pushed to the installed array of installed middleware. When a Loader is instantiated, it should probably clone the static private arrays of before and after middleware.

If you are okay with this approach, I'm happy to throw together a PR.
