### ISSUE TITLE
Loader failing if there are more items in queue than concurrency limit

### ISSUE THREAD

**Issue by tarling** [englercj/resource-loader#82]
With 3 spritesheets and concurrency set to 2, some of the tests are failing. Please see the following fork:

https://github.com/tarling/resource-loader

Run `npm run test` to run the slightly modified test

Will submit a PR if I can work out how to fix it

It seems quite similar to https://github.com/englercj/resource-loader/issues/7

Thanks

**Comment by tarling** [comment]
By making the following change (and analagous changes to the loader middleware in pixi), everything works. But there is possible a good reason why next was called in the image load callback.

https://github.com/tarling/resource-loader/commit/f732b5914a922600559efbedc647f8df6aefcb7c

**Comment by englercj** [comment]
Added a new test for this, which is currently failing. Hopefully I can fix this soon!

https://github.com/englercj/resource-loader/commit/576b81cb85bf1fe475e8881cd497487e16a05b5b

**Comment by englercj** [comment]
The fact that switching that next around fixes it gives me a hint as to the problem. However, I'm not sure I want to change that because it would mean that onProgress would go out with that resource as if it was completed, but it won't be because the subresources (that need to be parsed) haven't finished yet.

Looking into...

**Comment by englercj** [comment]
Ok, so this happens because since the concurrency is saturated it can't load the child resource that was added, as it is waiting for a concurrency slot to open. Since that child never loads, the parent never completes, and that slot never opens.

Maybe the solve here is to open the concurrency when it finishes loading and is running middleware.

**Comment by tarling** [comment]
Thanks for fixing this so quickly @englercj
