### ISSUE TITLE
Some urls don't return an img when loaded

### ISSUE THREAD

**Issue by nuthinking** [englercj/resource-loader#85]
I am using this loader with Pixi.js and loading assets from the Web through a proxy. With certain url the loader doesn't return an img. In its data attribute in fact I find a blob looking like this:
![screen shot 2017-01-25 at 13 49 29](https://cloud.githubusercontent.com/assets/163635/22292845/2a2df96a-e305-11e6-9eb7-9d71c9aacea0.png)
It doesn't seem to be a problem with the proxy because a URL I have problem with works well when loaded and drawn on a canvas: http://codepen.io/anon/pen/egRwzK

Any idea why some urls don't load and how to fix it? Thanks!

**Comment by englercj** [comment]
Because we determine if it is an image automatically by parsing the URL. If we can't determine what the URL refers to, we default to using text XHR (which will load as a binary string). If you have a strange url (such as :large at the end of the extension) then you can tell resource loader it is supposed to be an image by passing a load type:

```js
const loader = new Loader();

loader.add('http://proxy.wisefac.es/https://pbs.twimg.com/media/C3BOhWuXUAAp63T.jpg:large', { loadType: Resource.LOAD_TYPE.IMAGE });
```

**Comment by nuthinking** [comment]
That's what was happening. Amazing!

Since we are here, is still the only option a CORS Proxy for such assets in Pixi?

Thanks a lot!

**Comment by englercj** [comment]
CORS issues are actually not because of pixi or resource-loader, but because of how Canvas2D and WebGL handle "dirty" canvases that use cross-domain images.

You can try using:

```
loader.add('http://...', { crossOrigin: true });
```

and for many people that works. If you need a specific [cross original value ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin) you can provide that as a string instead of passing `true`. Note that `true` uses the `anonymous` value.
